global using AOEOBasicDataLibrary.Civs.ViewModels;
global using BasicBlazorLibrary.Components.AutoCompleteHelpers;
global using BasicBlazorLibrary.Components.ComboTextboxes;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using Microsoft.AspNetCore.Components;
global using AOEOBasicDataLibrary.TestUtilities;
global using AOEOBasicDataLibrary.ViewModels;
global using System.Diagnostics.CodeAnalysis;
global using AOEOBasicDataLibrary.Civs.DataServices;
global using AOEOBasicDataLibrary.Services;
global using Microsoft.Extensions.DependencyInjection;
global using AOEOBasicDataLibrary.Civs.Models;
global using dd1 = AOEOBasicDataLibrary.Helpers.BasicGameLocationHelpers;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.HtmlParserClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.Misc;
global using CommonBasicLibraries.CollectionClasses;
global using cc1 = AOEOBasicDataLibrary.Helpers.CharacterHelpers;
global using AOEOBasicDataLibrary.Helpers;
global using System.Xml.Linq;
global using ll1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileLocator;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using QuestTesterLibrary.Extensions;
global using tt1 = QuestTesterLibrary.Helpers.TestTechPathClass;
global using QuestTesterLibrary.TestServices;
global using gg1 = AOEOBasicDataLibrary.Civs.Helpers.GlobalCivHelperClass;
global using QuestTesterLibrary.Helpers;
